### ISSUE TITLE
temp files writing error

### ISSUE THREAD

**Issue by tro-rugnl** [hammock-dev/hammock#14]
Hello, I am not very experienced with coding. I have my peptide sequences of phage display in a fasta file. I have successfully unzipped Hammock using WSL. I have given Hammock permission to write everywhere in the Hammock folder. When I try to run the example MUSI file following the instructions in the manual, it seems at first to be going fine but then I get the following error (copied below). Output folders are created in the dist folder but they are empty. I'm not sure what is going wrong and I would be very grateful if you can help me.

2023-12-22 18:51:15.505:	java.io.IOException: java.io.FileNotFoundException: /tmp/Hammock_temp_1703267464501/msa/0.aln (No such file or directory)
	at cz.krejciadam.hammock.FileIOManager.fileAsString(FileIOManager.java:1078)
	at cz.krejciadam.hammock.FileIOManager.getAllAlignmentLines(FileIOManager.java:772)
	at cz.krejciadam.hammock.FileIOManager.getAlignmentLines(FileIOManager.java:762)
	at cz.krejciadam.hammock.FileIOManager.getAlignmentsMap(FileIOManager.java:559)
	at cz.krejciadam.hammock.FileIOManager.saveClusterSequencesToCsv(FileIOManager.java:402)
	at cz.krejciadam.hammock.Hammock.runGreedyClustering(Hammock.java:429)
	at cz.krejciadam.hammock.Hammock.runFull(Hammock.java:376)
	at cz.krejciadam.hammock.Hammock.parseArgs(Hammock.java:271)
	at cz.krejciadam.hammock.Hammock.main(Hammock.java:145)
Caused by: java.io.FileNotFoundException: /tmp/Hammock_temp_1703267464501/msa/0.aln (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at cz.krejciadam.hammock.FileIOManager.fileAsString(FileIOManager.java:1071)
	... 8 more

**Comment by tro-rugnl** [comment]
I tried running everything on the university cluster and now it worked (Y). Seems to have been an issue with my home PC/ WSL environment.

**Comment by krejciadam** [comment]
Hi!
  For reference, this could be caused by permissions, as by default, Hammock tries to write to `/tmp`. See https://github.com/krejciadam/hammock/issues/3#issuecomment-881283173
