### ISSUE TITLE
java.io.IOException: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by gaborpapp89** [hammock-dev/hammock#3]
I ran hammock for the first time with the following option:

java -jar Hammock.jar full -i ./../../input.fasta

and i got the following error with alignment temporary file:

java.io.IOException: java.io.FileNotFoundException: /tmp/Hammock_temp_1626347683108/msa/3543.aln (No such file or directory)
        at cz.krejciadam.hammock.FileIOManager.fileAsString(FileIOManager.java:1078)
        at cz.krejciadam.hammock.FileIOManager.getAllAlignmentLines(FileIOManager.java:772)
        at cz.krejciadam.hammock.FileIOManager.getAlignmentLines(FileIOManager.java:762)
        at cz.krejciadam.hammock.FileIOManager.getAlignmentsMap(FileIOManager.java:559)
        at cz.krejciadam.hammock.FileIOManager.saveClusterSequencesToCsv(FileIOManager.java:402)
        at cz.krejciadam.hammock.Hammock.runClinkageClustering(Hammock.java:481)
        at cz.krejciadam.hammock.Hammock.runFull(Hammock.java:373)
        at cz.krejciadam.hammock.Hammock.parseArgs(Hammock.java:271)
        at cz.krejciadam.hammock.Hammock.main(Hammock.java:145)
Caused by: java.io.FileNotFoundException: /tmp/Hammock_temp_1626347683108/msa/3543.aln (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileReader.<init>(FileReader.java:72)
        at cz.krejciadam.hammock.FileIOManager.fileAsString(FileIOManager.java:1071)

Any help is appreciated...

Thank You!

**Comment by krejciadam** [comment]
Hi!
  From the message, it looks like some temporary alignment files are missing from their respective folder in `/tmp`. That can happen on some systems for various reasons. Can you try to change the temporary directory path to some safe location, i.e. place where you have write permissions and enough space? You can do it by editing `settings/settings.prop` file in the Hammock folder, uncommenting the `tempDirectory` line and putting some path there like this: 

change
`#tempDirectory=`

to
`tempDirectory=/path/to/somewhere`

**Comment by gaborpapp89** [comment]
Hi!

Thank you for the suggestion. I changed the temporary path, but the same error message showed up again. I forgot to mention that I ran hammock in a wsl container on a windows machine. Maybe that's the problem? Thank You!

**Comment by krejciadam** [comment]
Hm, that could be the cause. Can you see the files mentioned in the error being created and staying in that location? Could be also path format problem maybe? Honestly, I have no experience whatsoever with WSL or Windows in general. In case you don't have access to a Unix-based machine, a full-featured virtual machine running e.g. on VirtualBox might be worth trying.

**Comment by gaborpapp89** [comment]
I tried on VirtualBox and it worked fine! Thank You!
